# Generated by Django 4.2.1 on 2023-06-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appTiendaWeb', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.IntegerField(blank=True)),
                ('cantidad', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTiendaWeb.carritocompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTiendaWeb.producto')),
            ],
        ),
    ]
