# Generated by Django 4.2.1 on 2023-06-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTiendaWeb', '0003_carritocompra_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, default='pendiente', max_length=50),
        ),
    ]
